title:              watsonthedev
# email:              your-email@example.com
description:        A repository for my thoughts as a software dev
author:             
baseurl:            "/"
url:                "https://watsonthedev.github.io"

# Social Profiles
twitter_username:   watsonthedev
github_username:    watsonthedev
# facebook_username:  
# instagram_username:  
linkedin_username: watsonthedev

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# markdown:           kramdown
# paginate:           5
# paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
